language: python

python:
  - "3.6"

env:
    global:
        - SPARK_HOME=/tmp/spark

before_install:
  - ./recommender/install_spark.sh

install:
  - pip install -r recommender/requirements.txt

before_script:
  - cd recommender

script:
  - pytest tests
